spring:
  application:
    name: Hello
  datasource:
    url: jdbc:mysql://47.111.3.30:3306/demo?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: demo
    password: Demo@2020
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9000

#…®√Ë≥÷æ√≤„xml
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml